SimpleBlog/Areas/Admin/ViewModels/Posts.cs
using SimpleBlog.Infrastructure;
using SimpleBlog.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace SimpleBlog.Areas.Admin.ViewModels
{
    public class tagCheckbox 
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public bool IsChecked { get; set; }
    }
    public class PostsIndex
    {
        public PagedData<Post> Posts { set; get; }
    }
    public class PostForm
    {
        public bool IsNew { get; set; }

        public int? PostId { get; set; }
            
        [Required,MaxLength(128)]
        public string Title { get; set; }
            
        [Required,MaxLength(128)]
        public string Slug { get; set; }
            
        [Required,DataType(DataType.MultilineText)]
        public string Content { get; set; }

        public IList<tagCheckbox> Tags { get; set; }



    }
}

SimpleBlog/Models/Post.cs
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
namespace SimpleBlog.Models
{
    public class Post
    { 
        public virtual int Id { set; get; }
        public virtual User User { set; get; }
        public virtual string Title { set; get; }
        public virtual string Slug { set; get; }
        public virtual string Content { set; get; }

        public virtual DateTime CreatedAt { set; get; }
        public virtual DateTime? UpdatedAt { set; get; }
        public virtual DateTime? DeletedAt { set; get; }
        public virtual bool IsDeleted { get { return DeletedAt != null; } }

        public virtual IList<Tag> Tags { set; get; }
        public Post()
        {
            Tags = new List<Tag>();
        }
    }

    public class PostMap : ClassMapping<Post> 
    {
        public PostMap() 
        {
            Table("posts");
            
            Id(x => x.Id, x => x.Generator(Generators.Identity));
            
            ManyToOne(x => x.User, x => 
            {
                x.Column("user_id");
                x.NotNullable(true);
            });

            Property(x => x.Title, x => x.NotNullable(true));
            Property(x => x.Slug, x => x.NotNullable(true));
            Property(x => x.Content, x => x.NotNullable(true));
            Property(x => x.CreatedAt, x =>
            {
                x.Column("created_at");
                x.NotNullable(true);
            });
            Property(x => x.UpdatedAt, x => x.Column("updated_at"));
            Property(x => x.DeletedAt, x => x.Column("deleted_at"));

            Bag(x => x.Tags, x => {
                x.Key(y=>y.Column("post_id"));
                x.Table("post_tags");
            },x=>x.ManyToMany(y=>y.Column("tag_id")));

        }
    }
}

SimpleBlog/ViewModels/Posts.cs
using SimpleBlog.Infrastructure;
using SimpleBlog.Models;
namespace SimpleBlog.ViewModels
{
    public class PostsIndex
    {
        public PagedData<Post> Posts { get; set; }

    }
    public class PostsShow {
        public Post Post { get; set; }
    }
    public class PostsTag
    {
        public Tag Tag { get; set; }
        public PagedData<Post> Posts { get; set; }
    }
}

SimpleBlog/Areas/Admin/Controllers/PostsController.cs
using SimpleBlog.Infrastructure;
using System.Web.Mvc;
using NHibernate.Linq;
using SimpleBlog.Models;
using System.Linq;

using SimpleBlog.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using SimpleBlog.Infrastructure.Extensions;
namespace SimpleBlog.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [SelectedTabAttribute("posts")]
    public class PostsController : Controller
    {
        private const int PostsPerPage = 10;
        public ActionResult Index(int page=1)
        {            
            var totalPostCount = Database.Session.Query<Post>().Count();

            var baseQuery = Database.Session.Query<Post>().OrderByDescending(f => f.CreatedAt);

            var postIds = baseQuery
                .Skip((page - 1) * PostsPerPage)
                .Take(PostsPerPage)
                .Select(p => p.Id)
                .ToArray();

            var CurrentPostPage = baseQuery
                .Where(p=>postIds.Contains(p.Id))
                .FetchMany(f=>f.Tags)
                .Fetch(f=>f.User)
                .ToList();

            PostsIndex a = new PostsIndex();
            a.Posts = new PagedData<Post>(CurrentPostPage, totalPostCount, page, PostsPerPage);            
            return View(a);

            //return View(new PostsIndex
            //{
            //    Posts = new PagedData<Post>(CurrentPostPage, totalPostCount, page, PostsPerPage)
            //});
        }
        public ActionResult New() 
        {
            return View("Form", new PostForm
            {
                IsNew = true,
                Tags = Database.Session.Query<Tag>().Select(tag => new tagCheckbox { 
                    Id=tag.Id,
                    Name=tag.Name,
                    IsChecked=false
                }).ToList()
            });
        }

        public ActionResult Edit(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();

            return View("Form", new PostForm
            {
                IsNew = false,
                PostId = post.Id,
                Content = post.Content,
                Slug = post.Slug,
                Title = post.Title,
                Tags = Database.Session.Query<Tag>().Select(tag => new tagCheckbox { 
                    Id=tag.Id,
                    Name=tag.Name,
                    IsChecked=post.Tags.Contains(tag)
                }).ToList()
            });
        }

        [HttpPost,ValidateAntiForgeryToken,ValidateInput(false)]
        public ActionResult Form(PostForm form) 
        {
            form.IsNew = form.PostId == null;

            if (!ModelState.IsValid)
                return View(form);

            var selectedTags = reconsileTags(form.Tags);

            Post post;

            if (form.IsNew) {
                post = new Post { 
                    CreatedAt= DateTime.Now,//DateTime.UtcNow,
                    User=Auth.User
                };

                foreach (var tag in selectedTags)
                    post.Tags.Add(tag);


            }
            else
            {
                post = Database.Session.Load<Post>(form.PostId);

                if (post == null)
                    return HttpNotFound();

                post.UpdatedAt = DateTime.UtcNow;

                foreach (var toAdd in selectedTags.Where(t => !post.Tags.Contains(t)))//not in post.Tags
                    post.Tags.Add(toAdd);

                foreach(var toRemove in post.Tags.Where(t=>!selectedTags.Contains(t)).ToList())
                    post.Tags.Remove(toRemove);
                 
            }

            post.Title = form.Title;
            post.Slug = form.Slug;
            post.Content = form.Content;

            Database.Session.SaveOrUpdate(post);
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryTokenAttribute]
        public ActionResult Trash(int id) 
        {
            Post post = Database.Session.Load<Post>(id);

            if (post == null)
               return HttpNotFound();

            post.DeletedAt = DateTime.UtcNow;

            Database.Session.Update(post);

            return RedirectToAction("Index");
        }
        
        [HttpPost, ValidateAntiForgeryTokenAttribute]
        public ActionResult Delete (int id)
        {
            Post post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            post.DeletedAt = DateTime.UtcNow;

            Database.Session.Delete(post);

            return RedirectToAction("Index");
        }

        public ActionResult Restore(int id)
        {
            Post post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            post.DeletedAt = null;

            Database.Session.Update(post);

            return RedirectToAction("Index");
        }
        private IEnumerable<Tag> reconsileTags(IEnumerable<tagCheckbox> Tags) {

            foreach (var tag in Tags.Where(t=>t.IsChecked)) 
            {
                if (tag.Id != null) {
                    yield return Database.Session.Load<Tag>(tag.Id);
                    continue;
                }
                var existingTag = Database.Session.Query<Tag>().FirstOrDefault(t => t.Name == tag.Name);
                if (existingTag != null)
                {
                    yield return existingTag;
                    continue;
                }
                var newTag=new Tag
                {
                    Name =tag.Name,
                    Slug = tag.Name.Slugify()
                };

                Database.Session.Save(newTag);
                yield return newTag;
            }
        }
	}
}

SimpleBlog/Controllers/PostsController.cs

using SimpleBlog.Models;
using System.Linq;
using NHibernate.Linq;
using System.Web.Mvc;
using SimpleBlog.ViewModels;
using SimpleBlog.Infrastructure;
using System.Text.RegularExpressions;
using System;

namespace SimpleBlog.Controllers
{
    public class PostsController:Controller
    {
        private const int PostsPerPage=5;
        public ActionResult Index(int page=1){
            var baseQuery =Database.Session.Query<Post>().Where(t=>t.DeletedAt==null).OrderByDescending(t=>t.CreatedAt);
            var totalPostCount = baseQuery.Count();
            var postIds = baseQuery.Skip((page - 1) * PostsPerPage).Take(PostsPerPage).Select(t => t.Id).ToArray();
            var posts = baseQuery.Where(t=>postIds.Contains(t.Id)).FetchMany(t=>t.Tags).Fetch(t=>t.User).ToList();

            return View(new PostsIndex() {
                Posts = new PagedData<Post>(posts,totalPostCount,page,PostsPerPage)
            });
        }
        public ActionResult Show(string idAndSlug) {
            var parts = SeparateIdAndSlug(idAndSlug);
            if (parts == null)
                return HttpNotFound();

            var post = Database.Session.Load<Post>(parts.Item1);
            if (post == null || post.IsDeleted)
                return HttpNotFound();
            if (!post.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                RedirectToRoutePermanent("Post", new { id = parts.Item1, slug = post.Slug });
            //-http://blog.dev/post/43-my-slug
            //-http://blog.dev/post/43-tes

            return View(new PostsShow {
                Post = post
            });
        }

        public ActionResult Tag(string idAndSlug,int page=1)
        {
            var parts = SeparateIdAndSlug(idAndSlug);
            if (parts == null)
                return HttpNotFound();

            var tag= Database.Session.Load<Tag>(parts.Item1);
            if (tag == null)
                return HttpNotFound();

            if (!tag.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                RedirectToRoutePermanent("Post", new { id = parts.Item1, slug = tag.Slug });

            var totalPostCount = tag.Posts.Count();

            var postIds = tag.Posts
                            .OrderByDescending(g=>g.CreatedAt)
                            .Skip((page - 1) * PostsPerPage)
                            .Take(PostsPerPage)
                            .Where(t=>t.DeletedAt==null)
                            .Select(t => t.Id).ToArray();

            var posts = Database.Session.Query<Post>()
                .OrderByDescending(b => b.CreatedAt)
                .Where(t => postIds.Contains(t.Id))
                .FetchMany(f => f.Tags)
                .Fetch(f => f.User)
                .ToList();

            return View(new PostsTag { 
                Tag=tag,
                Posts = new PagedData<Post>(posts, totalPostCount, page, PostsPerPage)
            });

        }

        private System.Tuple<int, string> SeparateIdAndSlug(string idAndSlug)
        {
            var matches = Regex.Match(idAndSlug, @"^(\d+)\-(.*)?$");

            if (!matches.Success)
                return null;

            var id = int.Parse(matches.Result("$1"));
            var slug = matches.Result("$2");

            return System.Tuple.Create(id, slug);
        }
    }
}

SimpleBlog/Areas/Admin/Views/Posts/Form.cshtml
@model SimpleBlog.Areas.Admin.ViewModels.PostForm
<h1>@(Model.IsNew?"Create Post":"Update Post")</h1>

@using (Html.BeginForm("Form","Posts")) 
{
    @Html.AntiForgeryToken()

    if (!Model.IsNew) 
    {
        @Html.HiddenFor(f => f.PostId)
    }
    
    <div class="row">
        <div class="col-lg-8">
            @Html.ValidationSummary()
            
            <div class="form-group">
                @Html.LabelFor(f=>f.Title)
                @Html.TextBoxFor(f => f.Title, new { @class="form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(f => f.Slug)
                @Html.TextBoxFor(f => f.Slug, new { @class = "form-control", data_slug = "#Title", @readonly = "readonly" })
            </div>

            <div class="form-group">
                @Html.LabelFor(f => f.Content)
                @Html.TextAreaFor(f => f.Content, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">Post Action</div>
                <div class="panel-body">
                    <input type="submit" value="@(Model.IsNew ? "Publish Post":"Update Post")" class="btn btn-success btn-sm"/>
                    Or 
                    <a href="@Url.Action("Index")">Cancel</a>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">Tags</div>
                <div class="panel-body post-tag-editor">
                    <label for="new-tag-name">New Tag:</label>
                     <div class="input-group">
                         <input id="new-tag-name" type="text" class="new-tag-name form-control" />
                         <span class="input-group-btn">
                             <button disabled class="btn btn-primary add-tag-button">Add</button>  
                         </span>
                     </div>
                    <ul class="tag-select">
                        <li class="template">
                            <a href="#" class="name" ></a>
                            <input type="hidden" class="name-input">
                            <input type="hidden" class="selected-input"/>
                        </li>

                        @for (var i = 0; i < Model.Tags.Count; i++) {
                            var tag = Model.Tags[i];
                            <li data-tag-id="@tag.Id" class="@(tag.IsChecked?"selected":"")">
                                <a href="#" >@tag.Name</a>
                                <input type="hidden" name="Tags[@(i)].Id" value="@tag.Id"/>
                                <input type="hidden" name="Tags[@(i)].Name" value="@tag.Name"/>
                                <input type="hidden" name="Tags[@(i)].IsChecked" value="@tag.IsChecked.ToString()" class="selected-input"/>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
{
    @Scripts.Render("~/admin/post/scripts")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Content")
    </script>
}

SimpleBlog/Areas/Admin/Views/Posts/Index.cshtml
@model SimpleBlog.Areas.Admin.ViewModels.PostsIndex

<h2>Posts</h2>
<div class="btn-toolbar" >
    <div class="btn-group">
        <a href="@Url.Action("new")" class="btn btn-primary btn-sm" ><i class="glyphicon glyphicon-plus"></i> Create Post</a>
    </div>
    <div class="btn-group pull-right">
        @if (Model.Posts.HasPreviousPage)
        {
            <a href="@Url.Action("Index", new { page = Model.Posts.PreviousPage })" class="btn btn-default btn-sm">
                <i class="glyphicon glyphicon-chevron-left" ></i>
                Prev Page
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Prev Page
            </a>
        }
        
        @if (Model.Posts.HasNextPage)
        {
            <a href="@Url.Action("Index", new { page = Model.Posts.NextPage })" class="btn btn-default btn-sm">
                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">
                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
                
            </a>
        }
</div>
</div>

<table class="table table-striped">
    <thead> 
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Tag</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model.Posts) 
        {
            var cls = "";
            if (post.IsDeleted) { cls = "danger"; }
                
            <tr class="@cls">
                <td>@post.Title</td>
                
                <td>@post.User.Username</td>
                <td>@string.Join(", ",post.Tags.Select(t => t.Name))</td>
                <td>@post.CreatedAt</td>
                <td>
                    <a href="@Url.Action("edit", new { post.Id})" class="btn btn-xs btn-primary">
                        <i class="glyphicon glyphicon-edit"></i> Edit                    
                    </a>
                    @if (!post.IsDeleted) { 
                        <div class="btn-group btn-group-xs" >
                            <a href="@Url.Action("trash", new { post.Id})" class="btn btn-danger" data-post="are you sure you want to trash this post? @post.Id">
                                <i class="glyphicon glyphicon-remove" ></i> Trash
                            </a>
                            <a href="#" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("delete", new { post.Id})" data-post="are you sure you want to delete this post FOREVER? @post.Id">
                                        <i class="glyphicon glyphicon-remove"></i> Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    }
                    else 
                    {
                        <a href="@Url.Action("restore", new { post.Id})" class="btn btn-xs btn-success" data-post="">
                            <i class="glyphicon glyphicon-plus-sign"></i> Restore
                        </a> 
                    }
                </td>
            </tr>
        }
    </tbody>
</table>