SimpleBlog/ViewModels/Layout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleBlog.ViewModels
{
    public class SideBarTag
    {
        public int Id { get;private set; }
        public string Name { get;private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }

        public SideBarTag(int id,string name,string slug,int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount;
        }
    }
    public class LayoutSidebar
    {
        public bool IsLoggedIn { get; set; }
        public string UserName { get; set; }
        public bool IsAdmin { get; set; }
        public IEnumerable<SideBarTag> Tags { get; set; }
    }
}

SimpleBlog/Controllers/LayoutController.cs
using NHibernate.Linq;
using System.Linq;
using SimpleBlog.Models;
using SimpleBlog.ViewModels;
using System.Web.Mvc;

namespace SimpleBlog.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            var layoutsidebar = new LayoutSidebar
            {
                IsLoggedIn = Auth.User != null,
                UserName = Auth.User != null ? Auth.User.Username : "",
                IsAdmin = User.IsInRole("admin"),

                Tags = Database.Session.Query<Tag>().Select(tag => new
                {
                    tag.Id,
                    tag.Name,
                    tag.Slug,
                    PostCount = tag.Posts.Count()
                }).Where(t => t.PostCount > 0).OrderByDescending(t => t.PostCount).Select(
                    tag => new SideBarTag(tag.Id, tag.Name, tag.Slug, tag.PostCount)).ToList()
            };

            return View(layoutsidebar);
        }
	}
}

SimpleBlog/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>@ViewBag.Title - SimpleBlog</title>
    @Styles.Render("~/Styles")

</head>
<body>
    
    <div class="site-header">
        <header class="container">
            <h1 class="page-header">
                <a href="@Url.RouteUrl("Home")">Awesome Stuff</a>
                <small>a simple blog powered by ASP.Net MVC</small>
            </h1>
        </header>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                @RenderBody()
            </div>
            <div class="col-lg-4 sidebar">
                @Html.Action("Sidebar","Layout")
            </div>
        </div>
        <footer>
            &copy; @DateTime.UtcNow.Year
        </footer>
    </div>

    @Scripts.Render("~/scripts");
    @RenderSection("Scripts", false)

</body>
</html>